import type { NavLink } from "../../types/nav.ts";

// This file is auto-generated by scripts/generate-work-links.ts
// Do not edit manually - run 'deno task generate-work-links' to update

const workLinks: ReadonlyArray<NavLink> = [
  {
    "href": "/work/reich-van-der-rohe-pavilion",
    "label": "Reich van Der Rohe Pavilion"
  },
  {
    "href": "/work/meri-in-pberg",
    "label": "Meri in Pberg"
  },
  {
    "href": "/work/sunchasing",
    "label": "Sunchasing"
  }
];

export const handler = () => {
  return new Response(JSON.stringify(workLinks), {
    headers: { "Content-Type": "application/json" },
  });
};
