import type { NavLink } from "../../types/nav.ts";

// This file is auto-generated by scripts/generate-work-links.ts
// Do not edit manually - run 'deno task generate-work-links' to update

const workLinks: ReadonlyArray<NavLink> = [
  {
    "href": "/work/a-blossom-drowning",
    "label": "A Blossom Drowning",
  },
  {
    "href": "/work/coron",
    "label": "Coron",
  },
  {
    "href": "/work/e--amp-c",
    "label": "E&C",
  },
  {
    "href": "/work/loyola-retreat-house",
    "label": "Loyola Retreat House",
  },
  {
    "href": "/work/meri-in-pberg",
    "label": "Meri in Pberg",
  },
  {
    "href": "/work/niemeyer-in-rio",
    "label": "Niemeyer in Rio",
  },
  {
    "href": "/work/ornate",
    "label": "Ornate",
  },
  {
    "href": "/work/reich--van-der-rohe-pavilion",
    "label": "Reich-Van der Rohe Pavilion",
  },
  {
    "href": "/work/sunchasing",
    "label": "Sunchasing",
  },
];

export const handler = () => {
  return new Response(JSON.stringify(workLinks), {
    headers: { "Content-Type": "application/json" },
  });
};
