const capitalizeWords = (str: string): string => {
  const lowercaseWords = new Set([
    "a",
    "an",
    "and",
    "as",
    "at",
    "but",
    "by",
    "for",
    "from",
    "in",
    "into",
    "of",
    "on",
    "or",
    "the",
    "to",
    "with",
    "der",
  ]);

  const capitalizeSegment = (
    segment: string,
    isFirstSegment: boolean,
  ): string => {
    const words = segment.split("-");

    return words
      .map((word, index) => {
        const lowerWord = word.toLowerCase();
        const isFirstWord = isFirstSegment && index === 0;
        const shouldCapitalize = isFirstWord || !lowercaseWords.has(lowerWord);

        return shouldCapitalize
          ? word.charAt(0).toUpperCase() + word.slice(1).toLowerCase()
          : lowerWord;
      })
      .join(" ");
  };

  const segments = str.split("--");

  return segments
    .map((segment, index) => capitalizeSegment(segment, index === 0))
    .join("-");
};

const generateWorkLinks = async () => {
  const workDir = new URL("../routes/work", import.meta.url).pathname;
  const entries = [];

  for await (const entry of Deno.readDir(workDir)) {
    if (entry.isFile && entry.name.endsWith(".tsx")) {
      const fileName = entry.name.replace(".tsx", "");
      entries.push({
        href: `/work/${fileName}`,
        label: capitalizeWords(fileName),
      });
    }
  }

  const fileContent = `import type { NavLink } from "../../types/nav.ts";

// This file is auto-generated by scripts/generate-work-links.ts
// Do not edit manually - run 'deno task generate-work-links' to update

const workLinks: ReadonlyArray<NavLink> = ${JSON.stringify(entries, null, 2)};

export const handler = () => {
  return new Response(JSON.stringify(workLinks), {
    headers: { "Content-Type": "application/json" },
  });
};
`;

  const outputPath = new URL(
    "../routes/api/work-links.ts",
    import.meta.url,
  ).pathname;

  await Deno.writeTextFile(outputPath, fileContent);
  console.log(`✓ Generated work-links.ts with ${entries.length} entries`);
};

await generateWorkLinks();
